// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Appuser
{
    public int Appuserid { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public int? Role { get; set; }

    public string Displayname { get; set; }

    public string Avatar { get; set; }

    public bool? Isdeleted { get; set; }
}