// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CafeManager.Core.Data;

public partial class Coffeetable
{
    [NotMapped]
    public string Tablename { get; set; }

    public int Coffeetableid { get; set; }

    public string Statustable { get; set; }

    public string Notes { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();
}