// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Consumedmaterial
{
    public int Consumedmaterialid { get; set; }

    public int? Materialsupplierid { get; set; }

    public decimal? Quantity { get; set; }

    public bool? Isdeleted { get; set; }

    public DateOnly Usagedate { get; set; }

    public virtual Materialsupplier Materialsupplier { get; set; }
}