// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Customer
{
    public int Customerid { get; set; }

    public string Displayname { get; set; }

    public DateTime? Buydate { get; set; }

    public string Type { get; set; }

    public decimal? Totalspent { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();
}