// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Food
{
    public int Foodid { get; set; }

    public string Foodname { get; set; }

    public int Foodcategoryid { get; set; }

    public decimal? Price { get; set; }

    public byte[] Imagefood { get; set; }

    public decimal? Discountfood { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual Foodcategory Foodcategory { get; set; }

    public virtual ICollection<Invoicedetail> Invoicedetails { get; set; } = new List<Invoicedetail>();
}