// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Foodcategory
{
    public int Foodcategoryid { get; set; }

    public string Displayname { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual ICollection<Food> Foods { get; set; } = new List<Food>();
}