// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Importdetail
{
    public int Importdetailid { get; set; }

    public int Importid { get; set; }

    public int Materialid { get; set; }

    public decimal? Quantity { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual Import Import { get; set; }

    public virtual Material Material { get; set; }
}