// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Import
{
    public int Importid { get; set; }

    public string Deliveryperson { get; set; }

    public string Phone { get; set; }

    public string Shippingcompany { get; set; }

    public DateTime Receiveddate { get; set; }

    public string Receiver { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual ICollection<Importdetail> Importdetails { get; set; } = new List<Importdetail>();
}