// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Importdetail
{
    public int Importdetailid { get; set; }

    public int Importid { get; set; }

    public int Materialid { get; set; }

    public int Supplierid { get; set; }

    public int? Quantity { get; set; }

    public decimal? Unitprice { get; set; }

    public decimal? Totalprice { get; set; }

    public virtual Import Import { get; set; }

    public virtual Material Material { get; set; }

    public virtual Supplier Supplier { get; set; }
}