// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Invoicedetail
{
    public int Invoicedetailid { get; set; }

    public int? Invoiceid { get; set; }

    public int? Foodid { get; set; }

    public int? Quantity { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual Food Food { get; set; }

    public virtual Invoice Invoice { get; set; }
}