// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Materialsupplier
{
    public int Materialsupplierid { get; set; }

    public int Materialid { get; set; }

    public int Supplierid { get; set; }

    public DateTime? Manufacturedate { get; set; }

    public DateTime? Expirationdate { get; set; }

    public string Original { get; set; }

    public string Manufacturer { get; set; }

    public decimal? Price { get; set; }

    public bool? Isdeleted { get; set; }

    public virtual ICollection<Importdetail> Importdetails { get; set; } = new List<Importdetail>();

    public virtual Material Material { get; set; }

    public virtual Supplier Supplier { get; set; }
}