// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Materialsupplier
{
    public int Materialsupplierid { get; set; }

    public int Materialid { get; set; }

    public int Supplierid { get; set; }

    public DateOnly? Supplydate { get; set; }

    public decimal? Price { get; set; }

    public virtual Material Material { get; set; }

    public virtual Supplier Supplier { get; set; }
}