// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CafeManager.Core.Data;

public partial class Staff
{
    public int Staffid { get; set; }

    public string Staffname { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public char? Sex { get; set; }

    public DateOnly? Birthday { get; set; }

    public DateOnly? Startworking { get; set; }

    public string Role { get; set; }

    public string Workingstatus { get; set; }

    public decimal? Basicsalary { get; set; }

    public decimal? Workinghours { get; set; }

    public bool? Isdeleted { get; set; }
}